#!/usr/bin/env python3
import os

from configargparse import ArgumentParser

import rawlib


def _str_to_bool(text):
    """
    convert a string to boolean. 'true', 'TRUE', 'TrUe', 'Yes', '1', 'y' and
    similar returns True, otherwise returns False
    :param text: text to convert to boolean
    :return: the boolean representation of the text
    """
    return text.lower() in ['true', 'yes', 'y', '1']


def main():
    cfg_home = os.getenv('XDG_CONFIG_HOME', '~/.config')
    parser = ArgumentParser(default_config_files=[cfg_home + '/raw2jpg.conf'])
    parser.add_argument('directories', metavar='DIRECTORY', nargs='*',
                        help='Directory to process')
    parser.add_argument('-s', '--size', default=1920, type=int,
                        help='Size to generate the jpgs (max edge)')
    parser.add_argument('--overwrite', default=False, type=_str_to_bool,
                        help='Overwrite generated image if it already exists')
    args = parser.parse_args()

    for directory in args.directories:
        print("Generating jpgs from folder {} (size: {})".format(directory,
                                                                 args.size))
        rawlib.process_folder(directory,
                              size=args.size,
                              overwrite=args.overwrite)

if __name__ == '__main__':
    main()
